del *.bak /s
del *.ddk /s
del *.edk /s
del *.lst /s
del *.lnp /s
del *.mpf /s
del *.mpj /s
del *.obj /s
del *.omf /s
del JLinkSettings.ini /s
del *.plg /s
del *.rpt /s
del *.tmp /s
del *.__i /s
del *.crf /s
del *.o /s
del *.d /s
del *.axf /s
del *.tra /s
del *.dep /s
del JLinkLog.txt /s
del YC3121_Keil_asm.txt /s
del *.iex /s
del *.htm /s
del *.map /s
del YC3122_Keil.uvguix.* /s
del yc3122.BAT /s
del *._ia /s
del *.bin /s
del *.hex /s
del *.scvd /s
del *.elf /s
del YC3121_Keil.uvguix.* /s
del *.elf /s
rd /s /Q 